# 使用 ohrs 编译 WebRTC 客户端库到 td-webrtc 模块
Write-Host "开始使用 ohrs 编译 WebRTC 客户端..." -ForegroundColor Green

# 获取脚本所在目录
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

# 定位 webrtc_client 目录（在项目根目录的 webrtc 子目录中）
$WebrtcClientDir = Join-Path $ProjectRoot "webrtc\webrtc_client"

if (-not (Test-Path $WebrtcClientDir)) {
    Write-Host "错误：未找到 webrtc_client 目录：$WebrtcClientDir" -ForegroundColor Red
    Write-Host "请确保 td-webrtc 模块位于项目根目录下" -ForegroundColor Yellow
    exit 1
}

Write-Host "Rust 源码目录：$WebrtcClientDir" -ForegroundColor Cyan
Write-Host ""

# 进入 webrtc_client 目录进行编译
Set-Location $WebrtcClientDir

# 清理之前的构建
Write-Host "清理目标目录..." -ForegroundColor Yellow
Remove-Item -Path "target" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path "dist" -Recurse -Force -ErrorAction SilentlyContinue

# 使用 ohrs 构建
Write-Host "执行 ohrs build --release..." -ForegroundColor Yellow
ohrs build --release

if ($LASTEXITCODE -eq 0) {
    Write-Host "构建成功!" -ForegroundColor Green
    
    # 复制库文件到 td-webrtc 模块目录
    Write-Host "复制库文件到 td-webrtc 模块目录..." -ForegroundColor Yellow

    # td-webrtc 模块内的目标目录
    $moduleLibsBase = Join-Path $ScriptDir "libs"
    $moduleTypesDir = Join-Path $ScriptDir "src\types"
    $typeTargetFile = "$moduleTypesDir\libwebrtc_client.so.d.ts"

    # 确保目标目录存在
    New-Item -ItemType Directory -Path "$moduleLibsBase\arm64-v8a" -Force | Out-Null
    New-Item -ItemType Directory -Path "$moduleLibsBase\armeabi-v7a" -Force | Out-Null
    New-Item -ItemType Directory -Path "$moduleLibsBase\x86_64" -Force | Out-Null
    New-Item -ItemType Directory -Path $moduleTypesDir -Force | Out-Null

    # 复制各架构的库文件
    Copy-Item "dist\arm64-v8a\libwebrtc_client.so" "$moduleLibsBase\arm64-v8a\" -Force
    Copy-Item "dist\armeabi-v7a\libwebrtc_client.so" "$moduleLibsBase\armeabi-v7a\" -Force
    Copy-Item "dist\x86_64\libwebrtc_client.so" "$moduleLibsBase\x86_64\" -Force

    # 处理类型定义文件：将 index.d.ts 转换为 module 声明格式
    Write-Host "生成类型定义文件 (.d.ts)..." -ForegroundColor Yellow
    
    # 读取生成的 index.d.ts 内容
    $indexContent = Get-Content "dist\index.d.ts" -Raw
    
    # 移除原始文件的注释头
    $indexContent = $indexContent -replace '(?s)/\* auto-generated by OHOS-RS \*/\s*/\* eslint-disable \*/\s*', ''
    
    # 逐行处理，添加缩进并调整格式
    $lines = $indexContent -split "`r?`n"
    $processedLines = @()
    
    foreach ($line in $lines) {
        # 跳过空行和纯空格行
        if ([string]::IsNullOrWhiteSpace($line)) {
            $processedLines += ""
            continue
        }
        
        # 处理 export declare
        if ($line -match '^export declare ') {
            $processedLines += ($line -replace '^export declare ', '  export ')
        }
        # 处理 export class
        elseif ($line -match '^export class ') {
            $processedLines += ($line -replace '^export class ', '  export class ')
        }
        # 处理 export interface
        elseif ($line -match '^export interface ') {
            $processedLines += ($line -replace '^export interface ', '  export interface ')
        }
        # 处理 export type
        elseif ($line -match '^export type ') {
            $processedLines += ($line -replace '^export type ', '  export type ')
        }
        # 处理 export function
        elseif ($line -match '^exportfunction ') {
            $processedLines += ($line -replace '^exportfunction ', '  export function ')
        }
        # 处理函数声明（没有 export 的）
        elseif ($line -match '^  function ') {
            $processedLines += ($line -replace '^  function ', '    function ')
        }
        # 处理 constructor
        elseif ($line -match '^  constructor') {
            $processedLines += ($line -replace '^  constructor', '    constructor')
        }
        # 处理方法（以两个空格开头）
        elseif ($line -match '^  (\w+)\(') {
            $processedLines += ($line -replace '^  (\w+)\(', '    $1(')
        }
        # 处理注释块开始
        elseif ($line -match '^  /\*\*') {
            $processedLines += ($line -replace '^  /\*\*', '    /**')
        }
        # 处理注释块中间行
        elseif ($line -match '^    \*') {
            $processedLines += ($line -replace '^    \*', '      *')
        }
        # 处理闭合大括号
        elseif ($line -match '^}$') {
            $processedLines += '  }'
        }
        else {
            # 其他行保持不变
            $processedLines += $line
        }
    }
    
    # 重新组合
    $moduleContent = $processedLines -join "`n"
    
    # 生成最终的 .d.ts 文件
    $finalContent = @"
/* auto-generated by OHOS-RS */
/* eslint-disable */

declare module 'libwebrtc_client.so' {
$moduleContent
}
"@
    
    # 写入文件
    $finalContent | Out-File -FilePath $typeTargetFile -Encoding utf8 -NoNewline
    
    Write-Host "所有文件已成功复制到 td-webrtc 模块!" -ForegroundColor Green
    Write-Host "  - libs/arm64-v8a/libwebrtc_client.so" -ForegroundColor Cyan
    Write-Host "  - libs/armeabi-v7a/libwebrtc_client.so" -ForegroundColor Cyan
    Write-Host "  - libs/x86_64/libwebrtc_client.so" -ForegroundColor Cyan
    Write-Host "  - src/types/libwebrtc_client.so.d.ts" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "================================================" -ForegroundColor Green
    Write-Host "  构建完成！" -ForegroundColor Green
    Write-Host "================================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "下一步：" -ForegroundColor Yellow
    Write-Host "1. 在项目 oh-package.json5 中添加依赖：" -ForegroundColor White
    Write-Host '   "dependencies": {"td-webrtc": "file:./td-webrtc"}' -ForegroundColor Cyan
    Write-Host ""
    Write-Host "2. 在代码中导入使用：" -ForegroundColor White
    Write-Host "   import { WebRTC } from 'td-webrtc';" -ForegroundColor Cyan
    Write-Host ""
} else {
    Write-Host "构建失败!" -ForegroundColor Red
    exit 1
}
