/* auto-generated by OHOS-RS */
/* eslint-disable */

declare module 'libwebrtc_client.so' {
/** NAPI 解码输出帧 */
  export interface NapiDecodedFrame {
    /** I420 数据（二进制直传，无 base64 开销） */
  i420Data: ArrayBuffer
  width: number
  height: number
  timestampUs: number
  }

/** NAPI 导出：媒体帧（RTP 解包+帧重组后的完整帧） */
  export interface NapiMediaFrame {
  trackId: string
    /** 完整帧数据（VP8 raw / H264 Annex-B / 音频 PCM） */
  data: ArrayBuffer
  timestamp: number
  isKeyFrame: boolean
  isAudio: boolean
  payloadType: number
  ssrc: number
  }

  export interface NapiVideoDecoderConfig {
  width: number
  height: number
  }

  export interface NapiVideoEncoderConfig {
  width: number
  height: number
  frameRate: number
    /** 比特率（bps），使用 f64 因为 JS 不支持 u64 */
  bitRate: number
    /** 像素格式: "NV12" | "I420" | "RGBA" */
  pixelFormat?: string
    /** I帧间隔（毫秒） */
  iFrameInterval?: number
  }

/**
  * 检查设备支持的视频编码格式
  * 尝试创建各种 MIME 类型的编码器，返回支持的格式列表
  */
  export function checkSupportedVideoCodecs(): Array<string>

  export function getWebrtcVersion(): string

/**
  * 处理摄像头帧数据：去除 stride 对齐填充 + NV21 → NV12 转换
  *
  * 摄像头输出的数据格式为 NV21 (YUV_420_SP)：
  * - Y 平面: width * height 字节
  * - VU 交织平面: width * height / 2 字节 (VUVUVU...)
  *
  * 编码器需要 NV12 格式：
  * - Y 平面: width * height 字节
  * - UV 交织平面: width * height / 2 字节 (UVUVUV...)
  *
  * 当 stride != width 时，每行末尾有 (stride - width) 字节的填充数据需去除。
  *
  * 性能特点：
  * - chunks_exact_mut(2).swap(0,1) 编译为 ARM NEON vrev16 指令
  * - copy_from_slice 编译为 memcpy，走硬件级块拷贝
  * - Release 模式无 bounds check 开销
  *
  * @param src 摄像头原始 NV21 数据
  * @param width 图像宽度（像素）
  * @param height 图像高度（像素）
  * @param stride 行跨距（字节），可能 >= width
  * @return NV12 格式数据（无 stride 填充）
  */
  export function processCameraFrame(src: Uint8Array, width: number, height: number, stride: number): ArrayBuffer

/**
  * VP8 软件解码器
  *
  * 使用 libvpx 进行纯软件 VP8 解码。
  * 输入: VP8 编码数据
  * 输出: I420 格式 YUV 数据
  *
  * 注：由于 OHOS 设备普遍不支持 VP8 硬件解码，
  * 此实现使用 libvpx 软件解码器作为后备方案。
  */
  export class Vp8Decoder {
    /** 创建 VP8 解码器 */
    constructor()
    /** 初始化解码器 */
    initialize(config: NapiVideoDecoderConfig): boolean
    /**
      * 设置输出 Surface（通过 surfaceId）
      *
      * @param surface_id XComponent 的 surfaceId 字符串
      * @return 是否成功
      */
    setSurface(surfaceId: string): boolean
    /** 启动解码器 */
    start(): boolean
    /** 停止解码器 */
    stop(): boolean
    /**
      * 解码 VP8 帧
      *
      * @param vp8_data VP8 数据（Uint8Array 二进制直传，无 base64 开销）
      * @param timestamp_us 时间戳（微秒）
      * @param is_keyframe 是否为关键帧（用于刷新参考帧缓存）
      * @return 是否成功
      */
    decodeFrame(vp8Data: Uint8Array, timestampUs: number, isKeyframe?: boolean | undefined | null): boolean
    /**
      * 轮询解码输出
      *
      * @return 解码后的 I420 帧（二进制直传），如果没有则返回 null
      */
    pollOutput(): NapiDecodedFrame | null
    /**
      * 渲染解码输出到 Surface
      *
      * v30: 清空旧帧，只渲染最新一帧。
      * 防止解码器输出队列堆积导致渲染旧帧（低端设备花屏根因之一）。
      *
      * @return 是否成功渲染了一帧
      */
    renderToSurface(): boolean
  }
  export type VP8Decoder = Vp8Decoder

  export class WebRtcClient {
    /** 创建 Offer */
    createOffer(): string | null
    /** 创建 Answer */
    createAnswer(): string | null
    /** 设置本地 SDP */
    setLocalDescription(sdp: string, sdpType: string): boolean
    /** 设置远端 SDP */
    setRemoteDescription(sdp: string, sdpType: string): boolean
    isConnected(): boolean
    getConnectionState(): string
    setLocalAddress(addr: string): boolean
    /** 添加远端 ICE 候选 */
    addIceCandidate(candidate: string, sdpMid?: string | undefined | null, sdpMlineIndex?: number | undefined | null): boolean
    /** 创建数据通道 */
    createDataChannel(label: string, ordered?: boolean | undefined | null): boolean
    /** 通过数据通道发送消息 */
    sendMessage(channelLabel: string, message: string): boolean
    /** 接收数据通道消息 */
    receiveMessage(): string | null
    /**
      * 添加媒体轨道（音频或视频）到 PeerConnection
      *
      * - stream_id: 所属流 ID
      * - track_id: 轨道唯一 ID
      * - kind: "audio" 或 "video"
      * - codec_mime: MIME 类型，如 "video/VP8", "audio/opus"
      * - clock_rate: 时钟频率（视频 90000, opus 48000）
      * - channels: 音频声道数（视频填 0）
      * - ssrc: 同步源标识
      * - payload_type: RTP 载荷类型
      */
    addMediaTrack(streamId: string, trackId: string, kind: string, codecMime: string, clockRate: number, channels: number, ssrc: number, payloadType: number): boolean
    /** 移除媒体轨道 */
    removeMediaTrack(trackId: string): boolean
    /**
      * 发送 PCM 音频数据（一体化：G.711 编码 + RTP 打包 + 发送）
      *
      * 替代旧路径：ETS g711Encode → ETS sendEncodedAudioFrame
      * 新路径：单次 NAPI 调用，Rust 内部完成 G.711 编码 + RTP 打包 + handle_write
      *
      * - track_id: 音频轨道 ID
      * - pcm_data: PCM 16-bit LE 数据（Uint8Array）
      * - timestamp: RTP 时间戳
      */
    sendPcmAudio(trackId: string, pcmData: Uint8Array, timestamp: number): boolean
    /**
      * 轮询接收到的媒体帧（新 API）
      *
      * 返回 RTP 解包 + 帧重组后的完整媒体帧，消除 JSON/base64 开销
      */
    pollMediaFrames(): Array<NapiMediaFrame>
    /** 获取已添加的媒体轨道 ID 列表 */
    getMediaTracks(): Array<string>
    /**
      * 发送 RTCP PLI（Picture Loss Indication）请求关键帧
      *
      * 当解码器检测到花屏或丢包时，通过此方法通知发送端立即发送关键帧
      *
      * @param track_id 轨道 ID
      * @return 是否成功发送
      */
    sendRtcpPli(trackId: string): boolean
    /**
      * 创建内部视频编码器
      *
      * 根据 codec 参数创建 H264 硬编码或 VP8 软编码。
      * H264 初始化失败时自动回退到 VP8。
      *
      * @returns 实际使用的编解码器名称（"H264" 或 "VP8"），失败返回空字符串
      */
    createVideoEncoder(config: NapiVideoEncoderConfig, codec: string): string
    /** 启动内部视频编码器 */
    startVideoEncoder(): boolean
    /** 停止内部视频编码器 */
    stopVideoEncoder(): boolean
    /** 销毁内部视频编码器 */
    destroyVideoEncoder(): void
    /** 请求视频关键帧 */
    requestVideoKeyFrame(): boolean
    /** 获取内部视频编码器实际使用的编解码器 */
    getVideoEncoderCodec(): string
    /**
      * 视频编码 + RTP 打包 + 发送（一体化，单次 NAPI 调用）
      *
      * 替代旧路径：ETS encodeFrame + pollOutput + sendEncodedVideoFrame（3+ 次 NAPI）
      * 新路径：单次 NAPI 调用，Rust 内部完成 YUV 编码 + 输出 drain + RTP 打包 + handle_write
      *
      * - track_id: 视频轨道 ID
      * - yuv_data: YUV 帧数据（NV12/I420）
      * - timestamp_us: 输入时间戳（微秒）
      * - rtp_timestamp: RTP 时间戳（90kHz）
      * @returns 发送的 RTP 包总数，-1 表示失败
      */
    encodeAndSendVideo(trackId: string, yuvData: Uint8Array, timestampUs: number, rtpTimestamp: number): number
    /**
      * 处理内部事件（状态变化、ICE 候选等）
      *
      * 当 UDP 后台线程运行时，事件由后台线程处理，此方法直接返回。
      */
    processEvents(): void
    close(): boolean
    /**
      * 启动 UDP 网络层（零拷贝架构）
      *
      * UdpManager 内部完成：绑定端口 → 注册 ICE 候选 → 启动后台线程
      * 后台线程事件循环：UDP recv → handle_read → handle_timeout → poll → send
      *
      * @param port UDP 端口（0 = 系统分配随机端口）
      * @param device_ip 设备 IP（可选，为空时自动探测）
      * @return 本地 UDP 地址（"ip:port" 格式），失败返回 null
      */
    startUdp(port: number, deviceIp?: string | undefined | null): string | null
    /** 停止 UDP 网络层 */
    stopUdp(): void
    /** 获取 UDP 本地地址 */
    getLocalUdpAddress(): string | null
    pollEvent(): string | null
    pollAllEvents(): Array<string>
    /**
      * 构造函数：创建 WebRTC 客户端
      *
      * - stun_servers: STUN 服务器列表，如 ["stun:stun.l.google.com:19302"]
      * - turn_servers: TURN 服务器列表（可选）
      * - preferred_video_codec: 首选视频编解码器 ("VP8" 或 "H264")，决定 SDP 协商优先级
      *   先注册的编解码器在 SDP 中排在前面，对端优先选择。默认 "VP8"。
      */
    constructor(stunServers?: Array<string> | undefined | null, turnServers?: Array<string> | undefined | null, preferredVideoCodec?: string | undefined | null)
  }

/**
  * H.264 硬件解码器
  *
  * 使用 OpenHarmony OH_VideoDecoder 进行硬件加速 H.264 解码。
  * 输入: H.264 NALU 数据
  * 输出: Surface 渲染 (XComponent)
  */
  export class H264Decoder {
    /** 创建 H.264 解码器 */
    constructor()
    /**
      * 设置输出 Surface（通过指针）
      *
      * @param surface_ptr XComponent 的 NativeWindow 指针（转为 f64 传递，JS 不支持 usize）
      * @return 是否成功
      */
    setSurface(surfacePtr: number): boolean
    /**
      * 设置输出 Surface（通过 surfaceId）
      *
      * @param surface_id XComponent 的 surfaceId 字符串
      * @return 是否成功
      */
    setSurfaceById(surfaceId: string): boolean
    /**
      * 初始化解码器
      *
      * @param config 解码器配置
      * @return 是否成功
      */
    initialize(config: NapiVideoDecoderConfig): boolean
    /** 启动解码器 */
    start(): boolean
    /** 停止解码器 */
    stop(): boolean
    /**
      * 解码 H.264 帧
      *
      * @param nalu_data H.264 NALU 数据（Uint8Array 二进制直传，无 base64 开销）
      * @param timestamp_us 时间戳（微秒）
      * @param is_key_frame 是否为关键帧
      * @return 是否成功排队
      */
    decodeFrame(naluData: Uint8Array, timestampUs: number, isKeyFrame: boolean): boolean
    /** 销毁解码器，释放资源 */
    destroy(): void
  }


}